language: java
install: true
sudo: false
script: mvn clean verify

cache:
  directories:
  - $HOME/.m2
  
install:
  - mvn install -DfinalName=release -DskipTests=true -Dmaven.javadoc.skip=true -B -V
