language: java
install: true
script: mvn clean verify

install:
  - mvn install -DfinalName=release -DskipTests=false -Dmaven.javadoc.skip=true -B -V

cache:
  directories:
  - "$HOME/.m2"

deploy:
  provider: releases
  api_key: 
     secure: $SECURE_KEY
  file: target/SalesTax-1.0-SNAPSHOT.jar
  skip_cleanup: true
  on:
    tags: true
