language: java
install: true

install:
  - mvn install versions:set -DnewVersion=$TRAVIS_TAG -DfinalName=release -DskipTests=false -Dmaven.javadoc.skip=true -B -V

cache:
  directories:
  - $HOME/.m2

deploy:
  provider: releases
  api_key: 
     secure: $SECURE_KEY
  file: target/SalesTax-$TRAVIS_TAG.jar
  skip_cleanup: true
  on:
    tags: true


